#pragma line 1 "RTL_Banker_Algorithm/solution1/banker_algorithm.c" ::: -10
#pragma line 1 "RTL_Banker_Algorithm/solution1/banker_algorithm.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "RTL_Banker_Algorithm/solution1/banker_algorithm.c" 2 ::: 184
#pragma line 1 "RTL_Banker_Algorithm/solution1/banker_algorithm.h" 1 ::: 185
#pragma line 1 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 189
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 223
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 249
#pragma line 122 "/usr/include/features.h" 3 4 ::: 346
#pragma line 156 "/usr/include/features.h" 3 4 ::: 371
#pragma line 180 "/usr/include/features.h" 3 4 ::: 373
#pragma line 191 "/usr/include/features.h" 3 4 ::: 376
#pragma line 343 "/usr/include/features.h" 3 4 ::: 407
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 411
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 446
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 453
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 476
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 517
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 523
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 541
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 547
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 551
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 553
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 557
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 567
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 620
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 661
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 686
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 710
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 711
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 713
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 715
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 716
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 741
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 752
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 757
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 758
#pragma line 26 "/usr/include/stdint.h" 2 3 4 ::: 759
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 760
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 792
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 793
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 795
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 797
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 878
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 886
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 891
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 931
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 933
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 935
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 937
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 950
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 956
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 969
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 971
#pragma line 34 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 973
#pragma line 5 "RTL_Banker_Algorithm/solution1/banker_algorithm.h" 2 ::: 974
#pragma line 2 "RTL_Banker_Algorithm/solution1/banker_algorithm.c" 2 ::: 984
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 986
#pragma line 33 "/usr/include/stdio.h" 3 4 ::: 1008
#pragma line 1 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1009
#pragma line 56 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1050
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 1053
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1055
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1083
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1085
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1087
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1148
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1155
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1173
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1178
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1189
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1258
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1272
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1275
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1276
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1308
#pragma line 1 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1324
#pragma line 56 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1349
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1352
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1357
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1379
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1400
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1403
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1414
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1424
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1426
#pragma line 1 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1430
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1479
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1480
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1486
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1488
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1508
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1519
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1560
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1590
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1616
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1620
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1635
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1647
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1653
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1655
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1665
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1687
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1703
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1720
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1752
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1798
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1812
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1815
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1891
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1930
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1971
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 2084
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 2147
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2196
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 2207
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2237
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2265
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2297
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2309
#pragma line 4 "RTL_Banker_Algorithm/solution1/banker_algorithm.c" 2 ::: 2312
