#pragma line 1 "RTL_Banker_Algorithm/solution1/banker_algorithm.c" ::: 0
#pragma line 1 "RTL_Banker_Algorithm/solution1/banker_algorithm.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "RTL_Banker_Algorithm/solution1/banker_algorithm.c" 2 ::: 194
#pragma line 1 "RTL_Banker_Algorithm/solution1/banker_algorithm.h" 1 ::: 195
#pragma line 1 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 199
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 233
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 259
#pragma line 122 "/usr/include/features.h" 3 4 ::: 356
#pragma line 156 "/usr/include/features.h" 3 4 ::: 381
#pragma line 180 "/usr/include/features.h" 3 4 ::: 383
#pragma line 191 "/usr/include/features.h" 3 4 ::: 386
#pragma line 343 "/usr/include/features.h" 3 4 ::: 417
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 421
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 456
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 463
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 486
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 527
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 533
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 551
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 557
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 561
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 563
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 567
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 577
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 630
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 671
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 696
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 720
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 721
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 723
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 725
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 726
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 751
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 762
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 767
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 768
#pragma line 26 "/usr/include/stdint.h" 2 3 4 ::: 769
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 770
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 802
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 803
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 805
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 807
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 888
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 896
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 901
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 941
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 943
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 945
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 947
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 960
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 966
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 979
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 981
#pragma line 34 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 983
#pragma line 5 "RTL_Banker_Algorithm/solution1/banker_algorithm.h" 2 ::: 984
#pragma line 2 "RTL_Banker_Algorithm/solution1/banker_algorithm.c" 2 ::: 994
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 996
#pragma line 33 "/usr/include/stdio.h" 3 4 ::: 1018
#pragma line 1 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1019
#pragma line 56 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1060
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 1063
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1065
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1093
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1095
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1097
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1158
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1165
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1183
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1188
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1199
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1268
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1282
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1285
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1286
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1318
#pragma line 1 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1334
#pragma line 56 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1359
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1362
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1367
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1389
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1410
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1413
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1424
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1434
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1436
#pragma line 1 "/mnt/B4A0CD3FA0CD08B6/Embedded/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1440
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1489
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1490
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1496
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1498
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1518
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1529
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1570
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1600
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1626
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1630
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1645
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1657
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1663
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1665
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1675
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1697
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1713
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1730
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1762
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1808
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1822
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1825
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1901
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1940
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1981
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 2094
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 2157
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2206
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 2217
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2247
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2275
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2307
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2319
#pragma line 4 "RTL_Banker_Algorithm/solution1/banker_algorithm.c" 2 ::: 2322
