#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("available_address0", 2, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("available_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("available_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("available_d0", 64, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("available_q0", 64, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("allocated_address0", 4, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("allocated_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("allocated_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("allocated_d0", 64, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("allocated_q0", 64, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("max_address0", 4, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("max_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("max_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("max_d0", 64, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("max_q0", 64, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("max_address1", 4, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("max_ce1", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("max_we1", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("max_d1", 64, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("max_q1", 64, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("need_address0", 4, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("need_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("need_q0", 64, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("ap_return", 64, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "banker_algorithm";
