// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "graph"
#define AUTOTB_TVIN_graph  "../tv/cdatafile/c.bellman_ford.autotvin_graph.dat"
// wrapc file define: "hwdist"
#define AUTOTB_TVIN_hwdist  "../tv/cdatafile/c.bellman_ford.autotvin_hwdist.dat"
#define AUTOTB_TVOUT_hwdist  "../tv/cdatafile/c.bellman_ford.autotvout_hwdist.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "hwdist"
#define AUTOTB_TVOUT_PC_hwdist  "../tv/rtldatafile/rtl.bellman_ford.autotvout_hwdist.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			graph_depth = 0;
			hwdist_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{graph " << graph_depth << "}\n";
			total_list << "{hwdist " << hwdist_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int graph_depth;
		int hwdist_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern "C" void bellman_ford (
float graph[10][10],
long long hwdist[10]);

extern "C" void AESL_WRAP_bellman_ford (
float graph[10][10],
long long hwdist[10])
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "hwdist"
		aesl_fh.read(AUTOTB_TVOUT_PC_hwdist, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_hwdist, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_hwdist, AESL_token); // data

			sc_bv<64> *hwdist_pc_buffer = new sc_bv<64>[10];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'hwdist', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'hwdist', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					hwdist_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_hwdist, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_hwdist))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: hwdist
				{
					// bitslice(63, 0)
					// {
						// celement: hwdist(63, 0)
						// {
							sc_lv<64>* hwdist_lv0_0_9_1 = new sc_lv<64>[10];
						// }
					// }

					// bitslice(63, 0)
					{
						int hls_map_index = 0;
						// celement: hwdist(63, 0)
						{
							// carray: (0) => (9) @ (1)
							for (int i_0 = 0; i_0 <= 9; i_0 += 1)
							{
								if (&(hwdist[0]) != NULL) // check the null address if the c port is array or others
								{
									hwdist_lv0_0_9_1[hls_map_index].range(63, 0) = sc_bv<64>(hwdist_pc_buffer[hls_map_index].range(63, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(63, 0)
					{
						int hls_map_index = 0;
						// celement: hwdist(63, 0)
						{
							// carray: (0) => (9) @ (1)
							for (int i_0 = 0; i_0 <= 9; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : hwdist[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : hwdist[0]
								// output_left_conversion : hwdist[i_0]
								// output_type_conversion : (hwdist_lv0_0_9_1[hls_map_index]).to_uint64()
								if (&(hwdist[0]) != NULL) // check the null address if the c port is array or others
								{
									hwdist[i_0] = (hwdist_lv0_0_9_1[hls_map_index]).to_uint64();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] hwdist_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "graph"
		char* tvin_graph = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_graph);

		// "hwdist"
		char* tvin_hwdist = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_hwdist);
		char* tvout_hwdist = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_hwdist);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_graph, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_graph, tvin_graph);

		sc_bv<32>* graph_tvin_wrapc_buffer = new sc_bv<32>[100];

		// RTL Name: graph
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: graph(31, 0)
				{
					// carray: (0) => (9) @ (1)
					for (int i_0 = 0; i_0 <= 9; i_0 += 1)
					{
						// carray: (0) => (9) @ (1)
						for (int i_1 = 0; i_1 <= 9; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : graph[i_0][i_1]
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : graph[0][0]
							// regulate_c_name       : graph
							// input_type_conversion : *(int*)&graph[i_0][i_1]
							if (&(graph[0][0]) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<32> graph_tmp_mem;
								graph_tmp_mem = *(int*)&graph[i_0][i_1];
								graph_tvin_wrapc_buffer[hls_map_index].range(31, 0) = graph_tmp_mem.range(31, 0);
                                 		       hls_map_index++;
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 100; i++)
		{
			sprintf(tvin_graph, "%s\n", (graph_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_graph, tvin_graph);
		}

		tcl_file.set_num(100, &tcl_file.graph_depth);
		sprintf(tvin_graph, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_graph, tvin_graph);

		// release memory allocation
		delete [] graph_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_hwdist, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_hwdist, tvin_hwdist);

		sc_bv<64>* hwdist_tvin_wrapc_buffer = new sc_bv<64>[10];

		// RTL Name: hwdist
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: hwdist(63, 0)
				{
					// carray: (0) => (9) @ (1)
					for (int i_0 = 0; i_0 <= 9; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : hwdist[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : hwdist[0]
						// regulate_c_name       : hwdist
						// input_type_conversion : hwdist[i_0]
						if (&(hwdist[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> hwdist_tmp_mem;
							hwdist_tmp_mem = hwdist[i_0];
							hwdist_tvin_wrapc_buffer[hls_map_index].range(63, 0) = hwdist_tmp_mem.range(63, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 10; i++)
		{
			sprintf(tvin_hwdist, "%s\n", (hwdist_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_hwdist, tvin_hwdist);
		}

		tcl_file.set_num(10, &tcl_file.hwdist_depth);
		sprintf(tvin_hwdist, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_hwdist, tvin_hwdist);

		// release memory allocation
		delete [] hwdist_tvin_wrapc_buffer;

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		bellman_ford(graph, hwdist);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_hwdist, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_hwdist, tvout_hwdist);

		sc_bv<64>* hwdist_tvout_wrapc_buffer = new sc_bv<64>[10];

		// RTL Name: hwdist
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: hwdist(63, 0)
				{
					// carray: (0) => (9) @ (1)
					for (int i_0 = 0; i_0 <= 9; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : hwdist[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : hwdist[0]
						// regulate_c_name       : hwdist
						// input_type_conversion : hwdist[i_0]
						if (&(hwdist[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> hwdist_tmp_mem;
							hwdist_tmp_mem = hwdist[i_0];
							hwdist_tvout_wrapc_buffer[hls_map_index].range(63, 0) = hwdist_tmp_mem.range(63, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 10; i++)
		{
			sprintf(tvout_hwdist, "%s\n", (hwdist_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_hwdist, tvout_hwdist);
		}

		tcl_file.set_num(10, &tcl_file.hwdist_depth);
		sprintf(tvout_hwdist, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_hwdist, tvout_hwdist);

		// release memory allocation
		delete [] hwdist_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "graph"
		delete [] tvin_graph;
		// release memory allocation: "hwdist"
		delete [] tvin_hwdist;
		delete [] tvout_hwdist;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

