lappend pragmaStatus0 {pragma "LOOP_TRIPCOUNT" source "/home/angelo/Desktop/SistemiEmbedded/VivadoHLSProject/ProjectFolder/RTL_mergesort.prj/solution1/mergesort.c" location "merge/MERGE_WHILE" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "LOOP_TRIPCOUNT" source "/home/angelo/Desktop/SistemiEmbedded/VivadoHLSProject/ProjectFolder/RTL_mergesort.prj/solution1/mergesort.c" location "merge/merge_label0" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'LOOP_TRIPCOUNT' cannot be applied: Label 'merge_label0' does not exist in function 'merge'. "}
lappend pragmaStatus2 {pragma "LOOP_TRIPCOUNT" source "/home/angelo/Desktop/SistemiEmbedded/VivadoHLSProject/ProjectFolder/RTL_mergesort.prj/solution1/mergesort.c" location "merge/merge_label1" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'LOOP_TRIPCOUNT' cannot be applied: Label 'merge_label1' does not exist in function 'merge'. "}
lappend pragmaStatus3 {pragma "LOOP_TRIPCOUNT" source "/home/angelo/Desktop/SistemiEmbedded/VivadoHLSProject/ProjectFolder/RTL_mergesort.prj/solution1/mergesort.c" location "merge/merge_label2" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'LOOP_TRIPCOUNT' cannot be applied: Label 'merge_label2' does not exist in function 'merge'. "}
lappend pragmaStatus4 {pragma "LOOP_TRIPCOUNT" source "/home/angelo/Desktop/SistemiEmbedded/VivadoHLSProject/ProjectFolder/RTL_mergesort.prj/solution1/mergesort.c" location "merge/MERGE_FOR1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "LOOP_TRIPCOUNT" source "/home/angelo/Desktop/SistemiEmbedded/VivadoHLSProject/ProjectFolder/RTL_mergesort.prj/solution1/mergesort.c" location "merge/MERGE_FOR2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "LOOP_TRIPCOUNT" source "/home/angelo/Desktop/SistemiEmbedded/VivadoHLSProject/ProjectFolder/RTL_mergesort.prj/solution1/mergesort.c" location "merge/MERGE_FOR3" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "LOOP_TRIPCOUNT" source "/home/angelo/Desktop/SistemiEmbedded/VivadoHLSProject/ProjectFolder/RTL_mergesort.prj/solution1/mergesort.c" location "mergesort/FOR2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "PIPELINE" source "/home/angelo/Desktop/SistemiEmbedded/VivadoHLSProject/ProjectFolder/RTL_mergesort.prj/solution1/mergesort.c" location "mergesort/FOR2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "ARRAY_PARTITION" source "/home/angelo/Desktop/SistemiEmbedded/VivadoHLSProject/ProjectFolder/RTL_mergesort.prj/solution1/mergesort.c" location "mergesort" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "arr"}
