// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern long int AESL_WRAP_banker_algorithm (
long int available[3],
long int allocated[4][3],
long int max[4][3],
long int need[4][3]);
