// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "bellman_ford.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic bellman_ford::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic bellman_ford::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<27> bellman_ford::ap_ST_fsm_state1 = "1";
const sc_lv<27> bellman_ford::ap_ST_fsm_state2 = "10";
const sc_lv<27> bellman_ford::ap_ST_fsm_state3 = "100";
const sc_lv<27> bellman_ford::ap_ST_fsm_state4 = "1000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state5 = "10000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state6 = "100000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state7 = "1000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state8 = "10000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state9 = "100000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state10 = "1000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state11 = "10000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state12 = "100000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<27> bellman_ford::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<32> bellman_ford::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> bellman_ford::ap_const_lv32_3 = "11";
const sc_lv<32> bellman_ford::ap_const_lv32_11 = "10001";
const sc_lv<32> bellman_ford::ap_const_lv32_C = "1100";
const sc_lv<32> bellman_ford::ap_const_lv32_16 = "10110";
const sc_lv<32> bellman_ford::ap_const_lv32_1 = "1";
const sc_lv<32> bellman_ford::ap_const_lv32_2 = "10";
const sc_lv<32> bellman_ford::ap_const_lv32_4 = "100";
const sc_lv<32> bellman_ford::ap_const_lv32_A = "1010";
const sc_lv<1> bellman_ford::ap_const_lv1_0 = "0";
const sc_lv<32> bellman_ford::ap_const_lv32_B = "1011";
const sc_lv<1> bellman_ford::ap_const_lv1_1 = "1";
const sc_lv<32> bellman_ford::ap_const_lv32_12 = "10010";
const sc_lv<32> bellman_ford::ap_const_lv32_13 = "10011";
const sc_lv<32> bellman_ford::ap_const_lv32_17 = "10111";
const sc_lv<32> bellman_ford::ap_const_lv32_18 = "11000";
const sc_lv<32> bellman_ford::ap_const_lv32_19 = "11001";
const sc_lv<4> bellman_ford::ap_const_lv4_0 = "0000";
const sc_lv<32> bellman_ford::ap_const_lv32_5 = "101";
const sc_lv<32> bellman_ford::ap_const_lv32_9 = "1001";
const sc_lv<63> bellman_ford::ap_const_lv63_0 = "000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> bellman_ford::ap_const_lv32_1A = "11010";
const sc_lv<64> bellman_ford::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> bellman_ford::ap_const_lv64_1 = "1";
const sc_lv<64> bellman_ford::ap_const_lv64_2 = "10";
const sc_lv<64> bellman_ford::ap_const_lv64_3 = "11";
const sc_lv<32> bellman_ford::ap_const_lv32_6 = "110";
const sc_lv<64> bellman_ford::ap_const_lv64_4 = "100";
const sc_lv<64> bellman_ford::ap_const_lv64_5 = "101";
const sc_lv<32> bellman_ford::ap_const_lv32_7 = "111";
const sc_lv<64> bellman_ford::ap_const_lv64_6 = "110";
const sc_lv<64> bellman_ford::ap_const_lv64_7 = "111";
const sc_lv<32> bellman_ford::ap_const_lv32_8 = "1000";
const sc_lv<64> bellman_ford::ap_const_lv64_8 = "1000";
const sc_lv<64> bellman_ford::ap_const_lv64_9 = "1001";
const sc_lv<64> bellman_ford::ap_const_lv64_7F = "1111111";
const sc_lv<32> bellman_ford::ap_const_lv32_10 = "10000";
const sc_lv<32> bellman_ford::ap_const_lv32_BF800000 = "10111111100000000000000000000000";
const sc_lv<3> bellman_ford::ap_const_lv3_0 = "000";
const sc_lv<4> bellman_ford::ap_const_lv4_A = "1010";
const sc_lv<4> bellman_ford::ap_const_lv4_1 = "1";
const sc_lv<32> bellman_ford::ap_const_lv32_1E = "11110";
const sc_lv<8> bellman_ford::ap_const_lv8_FF = "11111111";
const sc_lv<23> bellman_ford::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<63> bellman_ford::ap_const_lv63_1 = "1";
const sc_lv<32> bellman_ford::ap_const_lv32_1F = "11111";
const sc_lv<9> bellman_ford::ap_const_lv9_181 = "110000001";
const sc_lv<8> bellman_ford::ap_const_lv8_7F = "1111111";
const sc_lv<32> bellman_ford::ap_const_lv32_56 = "1010110";
const sc_lv<5> bellman_ford::ap_const_lv5_1 = "1";
const sc_lv<5> bellman_ford::ap_const_lv5_5 = "101";
const bool bellman_ford::ap_const_boolean_1 = true;

bellman_ford::bellman_ford(sc_module_name name) : sc_module(name), mVcdFile(0) {
    bellman_ford_faddbkb_U1 = new bellman_ford_faddbkb<1,5,32,32,32>("bellman_ford_faddbkb_U1");
    bellman_ford_faddbkb_U1->clk(ap_clk);
    bellman_ford_faddbkb_U1->reset(ap_rst);
    bellman_ford_faddbkb_U1->din0(reg_328);
    bellman_ford_faddbkb_U1->din1(reg_316);
    bellman_ford_faddbkb_U1->ce(ap_var_for_const0);
    bellman_ford_faddbkb_U1->dout(grp_fu_299_p2);
    bellman_ford_sitocud_U2 = new bellman_ford_sitocud<1,6,64,32>("bellman_ford_sitocud_U2");
    bellman_ford_sitocud_U2->clk(ap_clk);
    bellman_ford_sitocud_U2->reset(ap_rst);
    bellman_ford_sitocud_U2->din0(grp_fu_303_p0);
    bellman_ford_sitocud_U2->ce(ap_var_for_const0);
    bellman_ford_sitocud_U2->dout(grp_fu_303_p1);
    bellman_ford_fcmpdEe_U3 = new bellman_ford_fcmpdEe<1,1,32,32,1>("bellman_ford_fcmpdEe_U3");
    bellman_ford_fcmpdEe_U3->din0(grp_fu_308_p0);
    bellman_ford_fcmpdEe_U3->din1(grp_fu_308_p1);
    bellman_ford_fcmpdEe_U3->opcode(grp_fu_308_opcode);
    bellman_ford_fcmpdEe_U3->dout(grp_fu_308_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( exitcond_fu_474_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( exitcond_fu_474_p2 );

    SC_METHOD(thread_exitcond1_i_fu_369_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_i_reg_255 );

    SC_METHOD(thread_exitcond_fu_474_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( i_reg_277 );

    SC_METHOD(thread_exitcond_i_fu_395_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_i_reg_266 );

    SC_METHOD(thread_graph_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( graph_addr_reg_870 );
    sensitive << ( tmp_27_cast_fu_390_p1 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_graph_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_graph_load_1_to_int_fu_407_p1);
    sensitive << ( reg_316 );

    SC_METHOD(thread_graph_load_to_int_fu_543_p1);
    sensitive << ( reg_316 );

    SC_METHOD(thread_grp_fu_303_p0);
    sensitive << ( hwdist_q0 );
    sensitive << ( hwdist_q1 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fu_308_opcode);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_grp_fu_308_p0);
    sensitive << ( reg_316 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( x_assign_reg_908 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_grp_fu_308_p1);
    sensitive << ( reg_328 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_hwdist_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( hwdist_addr_10_reg_864 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( j_cast_fu_486_p1 );

    SC_METHOD(thread_hwdist_address1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( hwdist_addr_10_reg_864 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_hwdist_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_hwdist_ce1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_hwdist_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( p_Val2_4_fu_790_p3 );

    SC_METHOD(thread_hwdist_d1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_hwdist_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( or_cond_reg_934 );
    sensitive << ( exitcond1_i_fu_369_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_hwdist_we1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_i_fu_369_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_i_1_fu_375_p2);
    sensitive << ( i_i_reg_255 );

    SC_METHOD(thread_i_2_fu_480_p2);
    sensitive << ( i_reg_277 );

    SC_METHOD(thread_i_cast3_cast_fu_470_p1);
    sensitive << ( i_reg_277 );

    SC_METHOD(thread_i_cast3_fu_465_p1);
    sensitive << ( i_reg_277 );

    SC_METHOD(thread_isNeg_fu_691_p3);
    sensitive << ( sh_assign_fu_685_p2 );

    SC_METHOD(thread_j_1_fu_401_p2);
    sensitive << ( j_i_reg_266 );

    SC_METHOD(thread_j_2_fu_537_p2);
    sensitive << ( j_reg_288 );

    SC_METHOD(thread_j_cast_fu_486_p1);
    sensitive << ( j_reg_288 );

    SC_METHOD(thread_j_i_cast4_cast_fu_381_p1);
    sensitive << ( j_i_reg_266 );

    SC_METHOD(thread_loc_V_1_fu_631_p1);
    sensitive << ( p_Val2_s_fu_618_p1 );

    SC_METHOD(thread_loc_V_fu_621_p4);
    sensitive << ( p_Val2_s_fu_618_p1 );

    SC_METHOD(thread_notlhs1_fu_561_p2);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_18_fu_547_p4 );

    SC_METHOD(thread_notlhs7_fu_635_p2);
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( loc_V_fu_621_p4 );

    SC_METHOD(thread_notlhs9_fu_606_p2);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( tmp_11_fu_592_p4 );

    SC_METHOD(thread_notlhs_fu_425_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_1_fu_411_p4 );

    SC_METHOD(thread_notrhs1_fu_612_p2);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( tmp_29_fu_602_p1 );

    SC_METHOD(thread_notrhs2_fu_567_p2);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_30_fu_557_p1 );

    SC_METHOD(thread_notrhs8_fu_641_p2);
    sensitive << ( loc_V_1_fu_631_p1 );
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_notrhs_fu_431_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_19_fu_421_p1 );

    SC_METHOD(thread_or_cond_fu_668_p2);
    sensitive << ( tmp_23_reg_903 );
    sensitive << ( tmp_17_fu_663_p2 );

    SC_METHOD(thread_p_Val2_2_fu_774_p3);
    sensitive << ( isNeg_reg_943 );
    sensitive << ( tmp_28_fu_760_p1 );
    sensitive << ( tmp_31_fu_764_p4 );

    SC_METHOD(thread_p_Val2_4_fu_790_p3);
    sensitive << ( p_Result_s_reg_938 );
    sensitive << ( tmp_1_i_i_i_fu_781_p1 );
    sensitive << ( tmp_10_i_i_i_fu_784_p2 );

    SC_METHOD(thread_p_Val2_s_fu_618_p1);
    sensitive << ( x_assign_reg_908 );

    SC_METHOD(thread_p_shl1_cast_fu_359_p1);
    sensitive << ( tmp_9_fu_351_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_495_p3);
    sensitive << ( tmp_24_fu_491_p1 );

    SC_METHOD(thread_p_shl3_cast_fu_507_p3);
    sensitive << ( tmp_25_fu_503_p1 );

    SC_METHOD(thread_p_shl_cast_fu_347_p1);
    sensitive << ( tmp_5_fu_339_p3 );

    SC_METHOD(thread_sh_assign_1_cast_cas_fu_733_p1);
    sensitive << ( sh_assign_1_reg_948 );

    SC_METHOD(thread_sh_assign_1_cast_fu_730_p1);
    sensitive << ( sh_assign_1_reg_948 );

    SC_METHOD(thread_sh_assign_1_fu_709_p3);
    sensitive << ( isNeg_fu_691_p3 );
    sensitive << ( sh_assign_fu_685_p2 );
    sensitive << ( tmp_5_i_i_i_cast_fu_705_p1 );

    SC_METHOD(thread_sh_assign_fu_685_p2);
    sensitive << ( tmp_i_i_i_i_cast1_fu_681_p1 );

    SC_METHOD(thread_tmp_10_fu_363_p2);
    sensitive << ( p_shl1_cast_fu_359_p1 );
    sensitive << ( p_shl_cast_fu_347_p1 );

    SC_METHOD(thread_tmp_10_i_i_i_fu_784_p2);
    sensitive << ( tmp_1_i_i_i_fu_781_p1 );

    SC_METHOD(thread_tmp_11_fu_592_p4);
    sensitive << ( tmp_2_to_int_fu_588_p1 );

    SC_METHOD(thread_tmp_12_fu_385_p2);
    sensitive << ( tmp_10_reg_810 );
    sensitive << ( j_i_cast4_cast_fu_381_p1 );

    SC_METHOD(thread_tmp_13_fu_647_p2);
    sensitive << ( notrhs8_fu_641_p2 );
    sensitive << ( notlhs7_fu_635_p2 );

    SC_METHOD(thread_tmp_14_fu_653_p2);
    sensitive << ( notlhs9_reg_914 );
    sensitive << ( notrhs1_reg_919 );

    SC_METHOD(thread_tmp_15_fu_657_p2);
    sensitive << ( tmp_13_fu_647_p2 );
    sensitive << ( tmp_14_fu_653_p2 );

    SC_METHOD(thread_tmp_17_fu_663_p2);
    sensitive << ( tmp_16_reg_924 );
    sensitive << ( tmp_15_fu_657_p2 );

    SC_METHOD(thread_tmp_18_fu_547_p4);
    sensitive << ( graph_load_to_int_fu_543_p1 );

    SC_METHOD(thread_tmp_19_fu_421_p1);
    sensitive << ( graph_load_1_to_int_fu_407_p1 );

    SC_METHOD(thread_tmp_1_fu_411_p4);
    sensitive << ( graph_load_1_to_int_fu_407_p1 );

    SC_METHOD(thread_tmp_1_i_i_i_fu_781_p1);
    sensitive << ( p_Val2_2_reg_954 );

    SC_METHOD(thread_tmp_20_fu_573_p2);
    sensitive << ( notlhs1_reg_888 );
    sensitive << ( notrhs2_reg_893 );

    SC_METHOD(thread_tmp_22_fu_577_p2);
    sensitive << ( tmp_21_reg_898 );
    sensitive << ( tmp_20_fu_573_p2 );

    SC_METHOD(thread_tmp_23_fu_582_p2);
    sensitive << ( tmp_22_fu_577_p2 );

    SC_METHOD(thread_tmp_24_fu_491_p1);
    sensitive << ( j_reg_288 );

    SC_METHOD(thread_tmp_25_fu_503_p1);
    sensitive << ( j_reg_288 );

    SC_METHOD(thread_tmp_26_fu_515_p2);
    sensitive << ( p_shl3_cast_fu_507_p3 );
    sensitive << ( p_shl2_cast_fu_495_p3 );

    SC_METHOD(thread_tmp_27_cast_fu_390_p1);
    sensitive << ( tmp_12_fu_385_p2 );

    SC_METHOD(thread_tmp_27_fu_521_p2);
    sensitive << ( i_cast3_cast_reg_851 );
    sensitive << ( tmp_26_fu_515_p2 );

    SC_METHOD(thread_tmp_28_fu_760_p1);
    sensitive << ( tmp_35_fu_752_p3 );

    SC_METHOD(thread_tmp_29_fu_602_p1);
    sensitive << ( tmp_2_to_int_fu_588_p1 );

    SC_METHOD(thread_tmp_2_to_int_fu_588_p1);
    sensitive << ( reg_328 );

    SC_METHOD(thread_tmp_30_cast_fu_526_p1);
    sensitive << ( tmp_27_fu_521_p2 );

    SC_METHOD(thread_tmp_30_fu_557_p1);
    sensitive << ( graph_load_to_int_fu_543_p1 );

    SC_METHOD(thread_tmp_31_fu_764_p4);
    sensitive << ( tmp_i_i_i_fu_746_p2 );

    SC_METHOD(thread_tmp_35_fu_752_p3);
    sensitive << ( tmp_8_i_i_i_fu_740_p2 );

    SC_METHOD(thread_tmp_3_i_i_i_cast2_fu_726_p1);
    sensitive << ( tmp_3_i_i_i_fu_717_p4 );

    SC_METHOD(thread_tmp_3_i_i_i_fu_717_p4);
    sensitive << ( loc_V_1_reg_929 );

    SC_METHOD(thread_tmp_5_fu_339_p3);
    sensitive << ( i_i_reg_255 );

    SC_METHOD(thread_tmp_5_i_i_i_cast_fu_705_p1);
    sensitive << ( tmp_5_i_i_i_fu_699_p2 );

    SC_METHOD(thread_tmp_5_i_i_i_fu_699_p2);
    sensitive << ( loc_V_fu_621_p4 );

    SC_METHOD(thread_tmp_6_fu_437_p2);
    sensitive << ( notlhs_reg_836 );
    sensitive << ( notrhs_reg_841 );

    SC_METHOD(thread_tmp_7_i_i_i_fu_736_p1);
    sensitive << ( sh_assign_1_cast_fu_730_p1 );

    SC_METHOD(thread_tmp_8_fu_441_p2);
    sensitive << ( tmp_7_reg_846 );
    sensitive << ( tmp_6_fu_437_p2 );

    SC_METHOD(thread_tmp_8_i_i_i_fu_740_p2);
    sensitive << ( tmp_3_i_i_i_fu_717_p4 );
    sensitive << ( sh_assign_1_cast_cas_fu_733_p1 );

    SC_METHOD(thread_tmp_9_fu_351_p3);
    sensitive << ( i_i_reg_255 );

    SC_METHOD(thread_tmp_fu_531_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( j_cast_fu_486_p1 );
    sensitive << ( total_edges_fu_118 );

    SC_METHOD(thread_tmp_i_i_i_fu_746_p2);
    sensitive << ( tmp_3_i_i_i_cast2_fu_726_p1 );
    sensitive << ( tmp_7_i_i_i_fu_736_p1 );

    SC_METHOD(thread_tmp_i_i_i_i_cast1_fu_681_p1);
    sensitive << ( loc_V_fu_621_p4 );

    SC_METHOD(thread_total_edges_1_fu_446_p2);
    sensitive << ( total_edges_fu_118 );

    SC_METHOD(thread_total_edges_2_fu_452_p3);
    sensitive << ( total_edges_fu_118 );
    sensitive << ( tmp_8_fu_441_p2 );
    sensitive << ( total_edges_1_fu_446_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( exitcond_fu_474_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_fu_531_p2 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( or_cond_fu_668_p2 );
    sensitive << ( exitcond_i_fu_395_p2 );
    sensitive << ( exitcond1_i_fu_369_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "bellman_ford_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, graph_address0, "(port)graph_address0");
    sc_trace(mVcdFile, graph_ce0, "(port)graph_ce0");
    sc_trace(mVcdFile, graph_q0, "(port)graph_q0");
    sc_trace(mVcdFile, hwdist_address0, "(port)hwdist_address0");
    sc_trace(mVcdFile, hwdist_ce0, "(port)hwdist_ce0");
    sc_trace(mVcdFile, hwdist_we0, "(port)hwdist_we0");
    sc_trace(mVcdFile, hwdist_d0, "(port)hwdist_d0");
    sc_trace(mVcdFile, hwdist_q0, "(port)hwdist_q0");
    sc_trace(mVcdFile, hwdist_address1, "(port)hwdist_address1");
    sc_trace(mVcdFile, hwdist_ce1, "(port)hwdist_ce1");
    sc_trace(mVcdFile, hwdist_we1, "(port)hwdist_we1");
    sc_trace(mVcdFile, hwdist_d1, "(port)hwdist_d1");
    sc_trace(mVcdFile, hwdist_q1, "(port)hwdist_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, reg_316, "reg_316");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, grp_fu_303_p1, "grp_fu_303_p1");
    sc_trace(mVcdFile, reg_328, "reg_328");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, tmp_10_fu_363_p2, "tmp_10_fu_363_p2");
    sc_trace(mVcdFile, tmp_10_reg_810, "tmp_10_reg_810");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_1_fu_375_p2, "i_1_fu_375_p2");
    sc_trace(mVcdFile, i_1_reg_818, "i_1_reg_818");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, j_1_fu_401_p2, "j_1_fu_401_p2");
    sc_trace(mVcdFile, j_1_reg_831, "j_1_reg_831");
    sc_trace(mVcdFile, notlhs_fu_425_p2, "notlhs_fu_425_p2");
    sc_trace(mVcdFile, notlhs_reg_836, "notlhs_reg_836");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, notrhs_fu_431_p2, "notrhs_fu_431_p2");
    sc_trace(mVcdFile, notrhs_reg_841, "notrhs_reg_841");
    sc_trace(mVcdFile, grp_fu_308_p2, "grp_fu_308_p2");
    sc_trace(mVcdFile, tmp_7_reg_846, "tmp_7_reg_846");
    sc_trace(mVcdFile, i_cast3_cast_fu_470_p1, "i_cast3_cast_fu_470_p1");
    sc_trace(mVcdFile, i_cast3_cast_reg_851, "i_cast3_cast_reg_851");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, i_2_fu_480_p2, "i_2_fu_480_p2");
    sc_trace(mVcdFile, i_2_reg_859, "i_2_reg_859");
    sc_trace(mVcdFile, hwdist_addr_10_reg_864, "hwdist_addr_10_reg_864");
    sc_trace(mVcdFile, exitcond_fu_474_p2, "exitcond_fu_474_p2");
    sc_trace(mVcdFile, graph_addr_reg_870, "graph_addr_reg_870");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, j_2_fu_537_p2, "j_2_fu_537_p2");
    sc_trace(mVcdFile, j_2_reg_878, "j_2_reg_878");
    sc_trace(mVcdFile, tmp_fu_531_p2, "tmp_fu_531_p2");
    sc_trace(mVcdFile, notlhs1_fu_561_p2, "notlhs1_fu_561_p2");
    sc_trace(mVcdFile, notlhs1_reg_888, "notlhs1_reg_888");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, notrhs2_fu_567_p2, "notrhs2_fu_567_p2");
    sc_trace(mVcdFile, notrhs2_reg_893, "notrhs2_reg_893");
    sc_trace(mVcdFile, tmp_21_reg_898, "tmp_21_reg_898");
    sc_trace(mVcdFile, tmp_23_fu_582_p2, "tmp_23_fu_582_p2");
    sc_trace(mVcdFile, tmp_23_reg_903, "tmp_23_reg_903");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, grp_fu_299_p2, "grp_fu_299_p2");
    sc_trace(mVcdFile, x_assign_reg_908, "x_assign_reg_908");
    sc_trace(mVcdFile, notlhs9_fu_606_p2, "notlhs9_fu_606_p2");
    sc_trace(mVcdFile, notlhs9_reg_914, "notlhs9_reg_914");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, notrhs1_fu_612_p2, "notrhs1_fu_612_p2");
    sc_trace(mVcdFile, notrhs1_reg_919, "notrhs1_reg_919");
    sc_trace(mVcdFile, tmp_16_reg_924, "tmp_16_reg_924");
    sc_trace(mVcdFile, loc_V_1_fu_631_p1, "loc_V_1_fu_631_p1");
    sc_trace(mVcdFile, loc_V_1_reg_929, "loc_V_1_reg_929");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, or_cond_fu_668_p2, "or_cond_fu_668_p2");
    sc_trace(mVcdFile, or_cond_reg_934, "or_cond_reg_934");
    sc_trace(mVcdFile, p_Result_s_reg_938, "p_Result_s_reg_938");
    sc_trace(mVcdFile, isNeg_fu_691_p3, "isNeg_fu_691_p3");
    sc_trace(mVcdFile, isNeg_reg_943, "isNeg_reg_943");
    sc_trace(mVcdFile, sh_assign_1_fu_709_p3, "sh_assign_1_fu_709_p3");
    sc_trace(mVcdFile, sh_assign_1_reg_948, "sh_assign_1_reg_948");
    sc_trace(mVcdFile, p_Val2_2_fu_774_p3, "p_Val2_2_fu_774_p3");
    sc_trace(mVcdFile, p_Val2_2_reg_954, "p_Val2_2_reg_954");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, i_i_reg_255, "i_i_reg_255");
    sc_trace(mVcdFile, exitcond_i_fu_395_p2, "exitcond_i_fu_395_p2");
    sc_trace(mVcdFile, j_i_reg_266, "j_i_reg_266");
    sc_trace(mVcdFile, exitcond1_i_fu_369_p2, "exitcond1_i_fu_369_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, i_reg_277, "i_reg_277");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, j_reg_288, "j_reg_288");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, tmp_27_cast_fu_390_p1, "tmp_27_cast_fu_390_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, i_cast3_fu_465_p1, "i_cast3_fu_465_p1");
    sc_trace(mVcdFile, tmp_30_cast_fu_526_p1, "tmp_30_cast_fu_526_p1");
    sc_trace(mVcdFile, j_cast_fu_486_p1, "j_cast_fu_486_p1");
    sc_trace(mVcdFile, total_edges_fu_118, "total_edges_fu_118");
    sc_trace(mVcdFile, total_edges_2_fu_452_p3, "total_edges_2_fu_452_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, p_Val2_4_fu_790_p3, "p_Val2_4_fu_790_p3");
    sc_trace(mVcdFile, grp_fu_303_p0, "grp_fu_303_p0");
    sc_trace(mVcdFile, grp_fu_308_p0, "grp_fu_308_p0");
    sc_trace(mVcdFile, grp_fu_308_p1, "grp_fu_308_p1");
    sc_trace(mVcdFile, tmp_5_fu_339_p3, "tmp_5_fu_339_p3");
    sc_trace(mVcdFile, tmp_9_fu_351_p3, "tmp_9_fu_351_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_359_p1, "p_shl1_cast_fu_359_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_347_p1, "p_shl_cast_fu_347_p1");
    sc_trace(mVcdFile, j_i_cast4_cast_fu_381_p1, "j_i_cast4_cast_fu_381_p1");
    sc_trace(mVcdFile, tmp_12_fu_385_p2, "tmp_12_fu_385_p2");
    sc_trace(mVcdFile, graph_load_1_to_int_fu_407_p1, "graph_load_1_to_int_fu_407_p1");
    sc_trace(mVcdFile, tmp_1_fu_411_p4, "tmp_1_fu_411_p4");
    sc_trace(mVcdFile, tmp_19_fu_421_p1, "tmp_19_fu_421_p1");
    sc_trace(mVcdFile, tmp_6_fu_437_p2, "tmp_6_fu_437_p2");
    sc_trace(mVcdFile, tmp_8_fu_441_p2, "tmp_8_fu_441_p2");
    sc_trace(mVcdFile, total_edges_1_fu_446_p2, "total_edges_1_fu_446_p2");
    sc_trace(mVcdFile, tmp_24_fu_491_p1, "tmp_24_fu_491_p1");
    sc_trace(mVcdFile, tmp_25_fu_503_p1, "tmp_25_fu_503_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_507_p3, "p_shl3_cast_fu_507_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_495_p3, "p_shl2_cast_fu_495_p3");
    sc_trace(mVcdFile, tmp_26_fu_515_p2, "tmp_26_fu_515_p2");
    sc_trace(mVcdFile, tmp_27_fu_521_p2, "tmp_27_fu_521_p2");
    sc_trace(mVcdFile, graph_load_to_int_fu_543_p1, "graph_load_to_int_fu_543_p1");
    sc_trace(mVcdFile, tmp_18_fu_547_p4, "tmp_18_fu_547_p4");
    sc_trace(mVcdFile, tmp_30_fu_557_p1, "tmp_30_fu_557_p1");
    sc_trace(mVcdFile, tmp_20_fu_573_p2, "tmp_20_fu_573_p2");
    sc_trace(mVcdFile, tmp_22_fu_577_p2, "tmp_22_fu_577_p2");
    sc_trace(mVcdFile, tmp_2_to_int_fu_588_p1, "tmp_2_to_int_fu_588_p1");
    sc_trace(mVcdFile, tmp_11_fu_592_p4, "tmp_11_fu_592_p4");
    sc_trace(mVcdFile, tmp_29_fu_602_p1, "tmp_29_fu_602_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_618_p1, "p_Val2_s_fu_618_p1");
    sc_trace(mVcdFile, loc_V_fu_621_p4, "loc_V_fu_621_p4");
    sc_trace(mVcdFile, notrhs8_fu_641_p2, "notrhs8_fu_641_p2");
    sc_trace(mVcdFile, notlhs7_fu_635_p2, "notlhs7_fu_635_p2");
    sc_trace(mVcdFile, tmp_13_fu_647_p2, "tmp_13_fu_647_p2");
    sc_trace(mVcdFile, tmp_14_fu_653_p2, "tmp_14_fu_653_p2");
    sc_trace(mVcdFile, tmp_15_fu_657_p2, "tmp_15_fu_657_p2");
    sc_trace(mVcdFile, tmp_17_fu_663_p2, "tmp_17_fu_663_p2");
    sc_trace(mVcdFile, tmp_i_i_i_i_cast1_fu_681_p1, "tmp_i_i_i_i_cast1_fu_681_p1");
    sc_trace(mVcdFile, sh_assign_fu_685_p2, "sh_assign_fu_685_p2");
    sc_trace(mVcdFile, tmp_5_i_i_i_fu_699_p2, "tmp_5_i_i_i_fu_699_p2");
    sc_trace(mVcdFile, tmp_5_i_i_i_cast_fu_705_p1, "tmp_5_i_i_i_cast_fu_705_p1");
    sc_trace(mVcdFile, tmp_3_i_i_i_fu_717_p4, "tmp_3_i_i_i_fu_717_p4");
    sc_trace(mVcdFile, sh_assign_1_cast_fu_730_p1, "sh_assign_1_cast_fu_730_p1");
    sc_trace(mVcdFile, sh_assign_1_cast_cas_fu_733_p1, "sh_assign_1_cast_cas_fu_733_p1");
    sc_trace(mVcdFile, tmp_3_i_i_i_cast2_fu_726_p1, "tmp_3_i_i_i_cast2_fu_726_p1");
    sc_trace(mVcdFile, tmp_7_i_i_i_fu_736_p1, "tmp_7_i_i_i_fu_736_p1");
    sc_trace(mVcdFile, tmp_8_i_i_i_fu_740_p2, "tmp_8_i_i_i_fu_740_p2");
    sc_trace(mVcdFile, tmp_35_fu_752_p3, "tmp_35_fu_752_p3");
    sc_trace(mVcdFile, tmp_i_i_i_fu_746_p2, "tmp_i_i_i_fu_746_p2");
    sc_trace(mVcdFile, tmp_28_fu_760_p1, "tmp_28_fu_760_p1");
    sc_trace(mVcdFile, tmp_31_fu_764_p4, "tmp_31_fu_764_p4");
    sc_trace(mVcdFile, tmp_1_i_i_i_fu_781_p1, "tmp_1_i_i_i_fu_781_p1");
    sc_trace(mVcdFile, tmp_10_i_i_i_fu_784_p2, "tmp_10_i_i_i_fu_784_p2");
    sc_trace(mVcdFile, grp_fu_308_opcode, "grp_fu_308_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("bellman_ford.hdltvin.dat");
    mHdltvoutHandle.open("bellman_ford.hdltvout.dat");
}

bellman_ford::~bellman_ford() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete bellman_ford_faddbkb_U1;
    delete bellman_ford_sitocud_U2;
    delete bellman_ford_fcmpdEe_U3;
}

void bellman_ford::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void bellman_ford::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_395_p2.read()))) {
        i_i_reg_255 = i_1_reg_818.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_i_reg_255 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_531_p2.read()))) {
        i_reg_277 = i_2_reg_859.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i_reg_277 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_i_reg_266 = j_1_reg_831.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_fu_369_p2.read()))) {
        j_i_reg_266 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        j_reg_288 = j_2_reg_878.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
                esl_seteq<1,1,1>(exitcond_fu_474_p2.read(), ap_const_lv1_0))) {
        j_reg_288 = ap_const_lv63_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        total_edges_fu_118 = total_edges_2_fu_452_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        total_edges_fu_118 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        graph_addr_reg_870 =  (sc_lv<7>) (tmp_30_cast_fu_526_p1.read());
        j_2_reg_878 = j_2_fu_537_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(exitcond_fu_474_p2.read(), ap_const_lv1_0))) {
        hwdist_addr_10_reg_864 =  (sc_lv<4>) (i_cast3_fu_465_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_1_reg_818 = i_1_fu_375_p2.read();
        tmp_10_reg_810 = tmp_10_fu_363_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        i_2_reg_859 = i_2_fu_480_p2.read();
        i_cast3_cast_reg_851 = i_cast3_cast_fu_470_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_fu_668_p2.read()))) {
        isNeg_reg_943 = sh_assign_fu_685_p2.read().range(8, 8);
        p_Result_s_reg_938 = p_Val2_s_fu_618_p1.read().range(31, 31);
        sh_assign_1_reg_948 = sh_assign_1_fu_709_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_1_reg_831 = j_1_fu_401_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        loc_V_1_reg_929 = loc_V_1_fu_631_p1.read();
        or_cond_reg_934 = or_cond_fu_668_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        notlhs1_reg_888 = notlhs1_fu_561_p2.read();
        notrhs2_reg_893 = notrhs2_fu_567_p2.read();
        tmp_21_reg_898 = grp_fu_308_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        notlhs9_reg_914 = notlhs9_fu_606_p2.read();
        notrhs1_reg_919 = notrhs1_fu_612_p2.read();
        tmp_16_reg_924 = grp_fu_308_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        notlhs_reg_836 = notlhs_fu_425_p2.read();
        notrhs_reg_841 = notrhs_fu_431_p2.read();
        tmp_7_reg_846 = grp_fu_308_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        p_Val2_2_reg_954 = p_Val2_2_fu_774_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        reg_316 = graph_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        reg_328 = grp_fu_303_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        tmp_23_reg_903 = tmp_23_fu_582_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        x_assign_reg_908 = grp_fu_299_p2.read();
    }
}

void bellman_ford::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void bellman_ford::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void bellman_ford::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void bellman_ford::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void bellman_ford::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void bellman_ford::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void bellman_ford::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void bellman_ford::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void bellman_ford::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void bellman_ford::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void bellman_ford::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void bellman_ford::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void bellman_ford::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void bellman_ford::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void bellman_ford::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void bellman_ford::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void bellman_ford::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void bellman_ford::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void bellman_ford::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void bellman_ford::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void bellman_ford::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void bellman_ford::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void bellman_ford::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_474_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void bellman_ford::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void bellman_ford::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_474_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void bellman_ford::thread_exitcond1_i_fu_369_p2() {
    exitcond1_i_fu_369_p2 = (!i_i_reg_255.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_255.read() == ap_const_lv4_A);
}

void bellman_ford::thread_exitcond_fu_474_p2() {
    exitcond_fu_474_p2 = (!i_reg_277.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_277.read() == ap_const_lv4_A);
}

void bellman_ford::thread_exitcond_i_fu_395_p2() {
    exitcond_i_fu_395_p2 = (!j_i_reg_266.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(j_i_reg_266.read() == ap_const_lv4_A);
}

void bellman_ford::thread_graph_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        graph_address0 = graph_addr_reg_870.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        graph_address0 =  (sc_lv<7>) (tmp_27_cast_fu_390_p1.read());
    } else {
        graph_address0 = "XXXXXXX";
    }
}

void bellman_ford::thread_graph_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        graph_ce0 = ap_const_logic_1;
    } else {
        graph_ce0 = ap_const_logic_0;
    }
}

void bellman_ford::thread_graph_load_1_to_int_fu_407_p1() {
    graph_load_1_to_int_fu_407_p1 = reg_316.read();
}

void bellman_ford::thread_graph_load_to_int_fu_543_p1() {
    graph_load_to_int_fu_543_p1 = reg_316.read();
}

void bellman_ford::thread_grp_fu_303_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        grp_fu_303_p0 = hwdist_q1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_303_p0 = hwdist_q0.read();
    } else {
        grp_fu_303_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void bellman_ford::thread_grp_fu_308_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        grp_fu_308_opcode = ap_const_lv5_5;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        grp_fu_308_opcode = ap_const_lv5_1;
    } else {
        grp_fu_308_opcode =  (sc_lv<5>) ("XXXXX");
    }
}

void bellman_ford::thread_grp_fu_308_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        grp_fu_308_p0 = x_assign_reg_908.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        grp_fu_308_p0 = reg_316.read();
    } else {
        grp_fu_308_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void bellman_ford::thread_grp_fu_308_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        grp_fu_308_p1 = reg_328.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        grp_fu_308_p1 = ap_const_lv32_BF800000;
    } else {
        grp_fu_308_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void bellman_ford::thread_hwdist_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        hwdist_address0 = hwdist_addr_10_reg_864.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        hwdist_address0 =  (sc_lv<4>) (j_cast_fu_486_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        hwdist_address0 =  (sc_lv<4>) (ap_const_lv64_9);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        hwdist_address0 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        hwdist_address0 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        hwdist_address0 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        hwdist_address0 =  (sc_lv<4>) (ap_const_lv64_1);
    } else {
        hwdist_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void bellman_ford::thread_hwdist_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        hwdist_address1 = hwdist_addr_10_reg_864.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        hwdist_address1 =  (sc_lv<4>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        hwdist_address1 =  (sc_lv<4>) (ap_const_lv64_8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        hwdist_address1 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        hwdist_address1 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        hwdist_address1 =  (sc_lv<4>) (ap_const_lv64_2);
    } else {
        hwdist_address1 =  (sc_lv<4>) ("XXXX");
    }
}

void bellman_ford::thread_hwdist_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        hwdist_ce0 = ap_const_logic_1;
    } else {
        hwdist_ce0 = ap_const_logic_0;
    }
}

void bellman_ford::thread_hwdist_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        hwdist_ce1 = ap_const_logic_1;
    } else {
        hwdist_ce1 = ap_const_logic_0;
    }
}

void bellman_ford::thread_hwdist_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        hwdist_d0 = p_Val2_4_fu_790_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        hwdist_d0 = ap_const_lv64_7F;
    } else {
        hwdist_d0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void bellman_ford::thread_hwdist_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        hwdist_d1 = ap_const_lv64_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        hwdist_d1 = ap_const_lv64_7F;
    } else {
        hwdist_d1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void bellman_ford::thread_hwdist_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_i_fu_369_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_reg_934.read())))) {
        hwdist_we0 = ap_const_logic_1;
    } else {
        hwdist_we0 = ap_const_logic_0;
    }
}

void bellman_ford::thread_hwdist_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_i_fu_369_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        hwdist_we1 = ap_const_logic_1;
    } else {
        hwdist_we1 = ap_const_logic_0;
    }
}

void bellman_ford::thread_i_1_fu_375_p2() {
    i_1_fu_375_p2 = (!i_i_reg_255.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_i_reg_255.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void bellman_ford::thread_i_2_fu_480_p2() {
    i_2_fu_480_p2 = (!i_reg_277.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_277.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void bellman_ford::thread_i_cast3_cast_fu_470_p1() {
    i_cast3_cast_fu_470_p1 = esl_zext<8,4>(i_reg_277.read());
}

void bellman_ford::thread_i_cast3_fu_465_p1() {
    i_cast3_fu_465_p1 = esl_zext<64,4>(i_reg_277.read());
}

void bellman_ford::thread_isNeg_fu_691_p3() {
    isNeg_fu_691_p3 = sh_assign_fu_685_p2.read().range(8, 8);
}

void bellman_ford::thread_j_1_fu_401_p2() {
    j_1_fu_401_p2 = (!j_i_reg_266.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_i_reg_266.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void bellman_ford::thread_j_2_fu_537_p2() {
    j_2_fu_537_p2 = (!ap_const_lv63_1.is_01() || !j_reg_288.read().is_01())? sc_lv<63>(): (sc_biguint<63>(ap_const_lv63_1) + sc_biguint<63>(j_reg_288.read()));
}

void bellman_ford::thread_j_cast_fu_486_p1() {
    j_cast_fu_486_p1 = esl_zext<64,63>(j_reg_288.read());
}

void bellman_ford::thread_j_i_cast4_cast_fu_381_p1() {
    j_i_cast4_cast_fu_381_p1 = esl_zext<8,4>(j_i_reg_266.read());
}

void bellman_ford::thread_loc_V_1_fu_631_p1() {
    loc_V_1_fu_631_p1 = p_Val2_s_fu_618_p1.read().range(23-1, 0);
}

void bellman_ford::thread_loc_V_fu_621_p4() {
    loc_V_fu_621_p4 = p_Val2_s_fu_618_p1.read().range(30, 23);
}

void bellman_ford::thread_notlhs1_fu_561_p2() {
    notlhs1_fu_561_p2 = (!tmp_18_fu_547_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_18_fu_547_p4.read() != ap_const_lv8_FF);
}

void bellman_ford::thread_notlhs7_fu_635_p2() {
    notlhs7_fu_635_p2 = (!loc_V_fu_621_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_fu_621_p4.read() != ap_const_lv8_FF);
}

void bellman_ford::thread_notlhs9_fu_606_p2() {
    notlhs9_fu_606_p2 = (!tmp_11_fu_592_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_11_fu_592_p4.read() != ap_const_lv8_FF);
}

void bellman_ford::thread_notlhs_fu_425_p2() {
    notlhs_fu_425_p2 = (!tmp_1_fu_411_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_1_fu_411_p4.read() != ap_const_lv8_FF);
}

void bellman_ford::thread_notrhs1_fu_612_p2() {
    notrhs1_fu_612_p2 = (!tmp_29_fu_602_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_29_fu_602_p1.read() == ap_const_lv23_0);
}

void bellman_ford::thread_notrhs2_fu_567_p2() {
    notrhs2_fu_567_p2 = (!tmp_30_fu_557_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_fu_557_p1.read() == ap_const_lv23_0);
}

void bellman_ford::thread_notrhs8_fu_641_p2() {
    notrhs8_fu_641_p2 = (!loc_V_1_fu_631_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_1_fu_631_p1.read() == ap_const_lv23_0);
}

void bellman_ford::thread_notrhs_fu_431_p2() {
    notrhs_fu_431_p2 = (!tmp_19_fu_421_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_19_fu_421_p1.read() == ap_const_lv23_0);
}

void bellman_ford::thread_or_cond_fu_668_p2() {
    or_cond_fu_668_p2 = (tmp_17_fu_663_p2.read() & tmp_23_reg_903.read());
}

void bellman_ford::thread_p_Val2_2_fu_774_p3() {
    p_Val2_2_fu_774_p3 = (!isNeg_reg_943.read()[0].is_01())? sc_lv<63>(): ((isNeg_reg_943.read()[0].to_bool())? tmp_28_fu_760_p1.read(): tmp_31_fu_764_p4.read());
}

void bellman_ford::thread_p_Val2_4_fu_790_p3() {
    p_Val2_4_fu_790_p3 = (!p_Result_s_reg_938.read()[0].is_01())? sc_lv<64>(): ((p_Result_s_reg_938.read()[0].to_bool())? tmp_10_i_i_i_fu_784_p2.read(): tmp_1_i_i_i_fu_781_p1.read());
}

void bellman_ford::thread_p_Val2_s_fu_618_p1() {
    p_Val2_s_fu_618_p1 = x_assign_reg_908.read();
}

void bellman_ford::thread_p_shl1_cast_fu_359_p1() {
    p_shl1_cast_fu_359_p1 = esl_zext<8,5>(tmp_9_fu_351_p3.read());
}

void bellman_ford::thread_p_shl2_cast_fu_495_p3() {
    p_shl2_cast_fu_495_p3 = esl_concat<5,3>(tmp_24_fu_491_p1.read(), ap_const_lv3_0);
}

void bellman_ford::thread_p_shl3_cast_fu_507_p3() {
    p_shl3_cast_fu_507_p3 = esl_concat<7,1>(tmp_25_fu_503_p1.read(), ap_const_lv1_0);
}

void bellman_ford::thread_p_shl_cast_fu_347_p1() {
    p_shl_cast_fu_347_p1 = esl_zext<8,7>(tmp_5_fu_339_p3.read());
}

void bellman_ford::thread_sh_assign_1_cast_cas_fu_733_p1() {
    sh_assign_1_cast_cas_fu_733_p1 = esl_sext<25,9>(sh_assign_1_reg_948.read());
}

void bellman_ford::thread_sh_assign_1_cast_fu_730_p1() {
    sh_assign_1_cast_fu_730_p1 = esl_sext<32,9>(sh_assign_1_reg_948.read());
}

void bellman_ford::thread_sh_assign_1_fu_709_p3() {
    sh_assign_1_fu_709_p3 = (!isNeg_fu_691_p3.read()[0].is_01())? sc_lv<9>(): ((isNeg_fu_691_p3.read()[0].to_bool())? tmp_5_i_i_i_cast_fu_705_p1.read(): sh_assign_fu_685_p2.read());
}

void bellman_ford::thread_sh_assign_fu_685_p2() {
    sh_assign_fu_685_p2 = (!tmp_i_i_i_i_cast1_fu_681_p1.read().is_01() || !ap_const_lv9_181.is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_i_i_i_i_cast1_fu_681_p1.read()) + sc_bigint<9>(ap_const_lv9_181));
}

void bellman_ford::thread_tmp_10_fu_363_p2() {
    tmp_10_fu_363_p2 = (!p_shl1_cast_fu_359_p1.read().is_01() || !p_shl_cast_fu_347_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl1_cast_fu_359_p1.read()) + sc_biguint<8>(p_shl_cast_fu_347_p1.read()));
}

void bellman_ford::thread_tmp_10_i_i_i_fu_784_p2() {
    tmp_10_i_i_i_fu_784_p2 = (!ap_const_lv64_0.is_01() || !tmp_1_i_i_i_fu_781_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(ap_const_lv64_0) - sc_biguint<64>(tmp_1_i_i_i_fu_781_p1.read()));
}

void bellman_ford::thread_tmp_11_fu_592_p4() {
    tmp_11_fu_592_p4 = tmp_2_to_int_fu_588_p1.read().range(30, 23);
}

void bellman_ford::thread_tmp_12_fu_385_p2() {
    tmp_12_fu_385_p2 = (!tmp_10_reg_810.read().is_01() || !j_i_cast4_cast_fu_381_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_10_reg_810.read()) + sc_biguint<8>(j_i_cast4_cast_fu_381_p1.read()));
}

void bellman_ford::thread_tmp_13_fu_647_p2() {
    tmp_13_fu_647_p2 = (notrhs8_fu_641_p2.read() | notlhs7_fu_635_p2.read());
}

void bellman_ford::thread_tmp_14_fu_653_p2() {
    tmp_14_fu_653_p2 = (notrhs1_reg_919.read() | notlhs9_reg_914.read());
}

void bellman_ford::thread_tmp_15_fu_657_p2() {
    tmp_15_fu_657_p2 = (tmp_13_fu_647_p2.read() & tmp_14_fu_653_p2.read());
}

void bellman_ford::thread_tmp_17_fu_663_p2() {
    tmp_17_fu_663_p2 = (tmp_15_fu_657_p2.read() & tmp_16_reg_924.read());
}

void bellman_ford::thread_tmp_18_fu_547_p4() {
    tmp_18_fu_547_p4 = graph_load_to_int_fu_543_p1.read().range(30, 23);
}

void bellman_ford::thread_tmp_19_fu_421_p1() {
    tmp_19_fu_421_p1 = graph_load_1_to_int_fu_407_p1.read().range(23-1, 0);
}

void bellman_ford::thread_tmp_1_fu_411_p4() {
    tmp_1_fu_411_p4 = graph_load_1_to_int_fu_407_p1.read().range(30, 23);
}

void bellman_ford::thread_tmp_1_i_i_i_fu_781_p1() {
    tmp_1_i_i_i_fu_781_p1 = esl_zext<64,63>(p_Val2_2_reg_954.read());
}

void bellman_ford::thread_tmp_20_fu_573_p2() {
    tmp_20_fu_573_p2 = (notrhs2_reg_893.read() | notlhs1_reg_888.read());
}

void bellman_ford::thread_tmp_22_fu_577_p2() {
    tmp_22_fu_577_p2 = (tmp_20_fu_573_p2.read() & tmp_21_reg_898.read());
}

void bellman_ford::thread_tmp_23_fu_582_p2() {
    tmp_23_fu_582_p2 = (tmp_22_fu_577_p2.read() ^ ap_const_lv1_1);
}

void bellman_ford::thread_tmp_24_fu_491_p1() {
    tmp_24_fu_491_p1 = j_reg_288.read().range(5-1, 0);
}

void bellman_ford::thread_tmp_25_fu_503_p1() {
    tmp_25_fu_503_p1 = j_reg_288.read().range(7-1, 0);
}

void bellman_ford::thread_tmp_26_fu_515_p2() {
    tmp_26_fu_515_p2 = (!p_shl3_cast_fu_507_p3.read().is_01() || !p_shl2_cast_fu_495_p3.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl3_cast_fu_507_p3.read()) + sc_biguint<8>(p_shl2_cast_fu_495_p3.read()));
}

void bellman_ford::thread_tmp_27_cast_fu_390_p1() {
    tmp_27_cast_fu_390_p1 = esl_zext<64,8>(tmp_12_fu_385_p2.read());
}

void bellman_ford::thread_tmp_27_fu_521_p2() {
    tmp_27_fu_521_p2 = (!tmp_26_fu_515_p2.read().is_01() || !i_cast3_cast_reg_851.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_26_fu_515_p2.read()) + sc_biguint<8>(i_cast3_cast_reg_851.read()));
}

void bellman_ford::thread_tmp_28_fu_760_p1() {
    tmp_28_fu_760_p1 = esl_zext<63,1>(tmp_35_fu_752_p3.read());
}

void bellman_ford::thread_tmp_29_fu_602_p1() {
    tmp_29_fu_602_p1 = tmp_2_to_int_fu_588_p1.read().range(23-1, 0);
}

void bellman_ford::thread_tmp_2_to_int_fu_588_p1() {
    tmp_2_to_int_fu_588_p1 = reg_328.read();
}

void bellman_ford::thread_tmp_30_cast_fu_526_p1() {
    tmp_30_cast_fu_526_p1 = esl_zext<64,8>(tmp_27_fu_521_p2.read());
}

void bellman_ford::thread_tmp_30_fu_557_p1() {
    tmp_30_fu_557_p1 = graph_load_to_int_fu_543_p1.read().range(23-1, 0);
}

void bellman_ford::thread_tmp_31_fu_764_p4() {
    tmp_31_fu_764_p4 = tmp_i_i_i_fu_746_p2.read().range(86, 24);
}

void bellman_ford::thread_tmp_35_fu_752_p3() {
    tmp_35_fu_752_p3 = tmp_8_i_i_i_fu_740_p2.read().range(24, 24);
}

void bellman_ford::thread_tmp_3_i_i_i_cast2_fu_726_p1() {
    tmp_3_i_i_i_cast2_fu_726_p1 = esl_zext<111,25>(tmp_3_i_i_i_fu_717_p4.read());
}

void bellman_ford::thread_tmp_3_i_i_i_fu_717_p4() {
    tmp_3_i_i_i_fu_717_p4 = esl_concat<24,1>(esl_concat<1,23>(ap_const_lv1_1, loc_V_1_reg_929.read()), ap_const_lv1_0);
}

void bellman_ford::thread_tmp_5_fu_339_p3() {
    tmp_5_fu_339_p3 = esl_concat<4,3>(i_i_reg_255.read(), ap_const_lv3_0);
}

void bellman_ford::thread_tmp_5_i_i_i_cast_fu_705_p1() {
    tmp_5_i_i_i_cast_fu_705_p1 = esl_sext<9,8>(tmp_5_i_i_i_fu_699_p2.read());
}

void bellman_ford::thread_tmp_5_i_i_i_fu_699_p2() {
    tmp_5_i_i_i_fu_699_p2 = (!ap_const_lv8_7F.is_01() || !loc_V_fu_621_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_7F) - sc_biguint<8>(loc_V_fu_621_p4.read()));
}

void bellman_ford::thread_tmp_6_fu_437_p2() {
    tmp_6_fu_437_p2 = (notrhs_reg_841.read() | notlhs_reg_836.read());
}

void bellman_ford::thread_tmp_7_i_i_i_fu_736_p1() {
    tmp_7_i_i_i_fu_736_p1 = esl_zext<111,32>(sh_assign_1_cast_fu_730_p1.read());
}

void bellman_ford::thread_tmp_8_fu_441_p2() {
    tmp_8_fu_441_p2 = (tmp_6_fu_437_p2.read() & tmp_7_reg_846.read());
}

void bellman_ford::thread_tmp_8_i_i_i_fu_740_p2() {
    tmp_8_i_i_i_fu_740_p2 = (!sh_assign_1_cast_cas_fu_733_p1.read().is_01())? sc_lv<25>(): tmp_3_i_i_i_fu_717_p4.read() >> (unsigned short)sh_assign_1_cast_cas_fu_733_p1.read().to_uint();
}

void bellman_ford::thread_tmp_9_fu_351_p3() {
    tmp_9_fu_351_p3 = esl_concat<4,1>(i_i_reg_255.read(), ap_const_lv1_0);
}

void bellman_ford::thread_tmp_fu_531_p2() {
    tmp_fu_531_p2 = (!j_cast_fu_486_p1.read().is_01() || !total_edges_fu_118.read().is_01())? sc_lv<1>(): (sc_bigint<64>(j_cast_fu_486_p1.read()) < sc_bigint<64>(total_edges_fu_118.read()));
}

void bellman_ford::thread_tmp_i_i_i_fu_746_p2() {
    tmp_i_i_i_fu_746_p2 = (!tmp_7_i_i_i_fu_736_p1.read().is_01())? sc_lv<111>(): tmp_3_i_i_i_cast2_fu_726_p1.read() << (unsigned short)tmp_7_i_i_i_fu_736_p1.read().to_uint();
}

void bellman_ford::thread_tmp_i_i_i_i_cast1_fu_681_p1() {
    tmp_i_i_i_i_cast1_fu_681_p1 = esl_zext<9,8>(loc_V_fu_621_p4.read());
}

void bellman_ford::thread_total_edges_1_fu_446_p2() {
    total_edges_1_fu_446_p2 = (!ap_const_lv64_1.is_01() || !total_edges_fu_118.read().is_01())? sc_lv<64>(): (sc_biguint<64>(ap_const_lv64_1) + sc_biguint<64>(total_edges_fu_118.read()));
}

void bellman_ford::thread_total_edges_2_fu_452_p3() {
    total_edges_2_fu_452_p3 = (!tmp_8_fu_441_p2.read()[0].is_01())? sc_lv<64>(): ((tmp_8_fu_441_p2.read()[0].to_bool())? total_edges_fu_118.read(): total_edges_1_fu_446_p2.read());
}

void bellman_ford::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_fu_369_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_395_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(exitcond_fu_474_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_531_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_668_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state27;
            } else {
                ap_NS_fsm = ap_ST_fsm_state26;
            }
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<27>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void bellman_ford::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"graph_address0\" :  \"" << graph_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"graph_ce0\" :  \"" << graph_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"graph_q0\" :  \"" << graph_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hwdist_address0\" :  \"" << hwdist_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hwdist_ce0\" :  \"" << hwdist_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hwdist_we0\" :  \"" << hwdist_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hwdist_d0\" :  \"" << hwdist_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"hwdist_q0\" :  \"" << hwdist_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hwdist_address1\" :  \"" << hwdist_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hwdist_ce1\" :  \"" << hwdist_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hwdist_we1\" :  \"" << hwdist_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hwdist_d1\" :  \"" << hwdist_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"hwdist_q1\" :  \"" << hwdist_q1.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

